import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from datetime import datetime


def export_to_excel(data, fields, output_path="output.xlsx"):
    """
    data   : list of dicts from extractor
    fields : list of field names the user chose e.g. ["Name", "Serial No."]
    Writes a styled .xlsx and returns the path.
    """
    wb = openpyxl.Workbook()

    # ── Sheet 1: Extracted Data ───────────────────────────────
    ws = wb.active
    ws.title = "Extracted Data"

    headers = ["#", "File"] + fields
    header_fill = PatternFill("solid", fgColor="1D9E75")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    alt_fill    = PatternFill("solid", fgColor="E1F5EE")

    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.fill      = header_fill
        cell.font      = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    ws.row_dimensions[1].height = 22

    for i, row in enumerate(data, 1):
        row_num = i + 1
        fill = alt_fill if i % 2 == 0 else None

        values = [i, row.get("file", "")]
        for f in fields:
            values.append(row.get(f, "—"))

        for col, val in enumerate(values, 1):
            cell = ws.cell(row=row_num, column=col, value=val)
            cell.alignment = Alignment(vertical="center")
            if fill:
                cell.fill = fill

    # Auto column widths
    for col in ws.columns:
        max_len = 0
        col_letter = col[0].column_letter
        for cell in col:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 4, 40)

    ws.freeze_panes = "A2"

    # ── Sheet 2: Summary ─────────────────────────────────────
    ws2 = wb.create_sheet("Summary")
    ws2.column_dimensions["A"].width = 28
    ws2.column_dimensions["B"].width = 24

    summary_data = [
        ("Extraction Summary", ""),
        ("", ""),
        ("Total files processed",  len(data)),
        ("Fields extracted",       ", ".join(fields)),
        ("Date & Time",            datetime.now().strftime("%d %b %Y, %I:%M %p")),
        ("Generated by",           "ID-RSS — Intelligent Document Retrieval & Structuring System"),
    ]

    title_font  = Font(bold=True, size=13, color="0F6E56")
    label_font  = Font(bold=True, size=11)

    for row_num, (label, value) in enumerate(summary_data, 1):
        cell_a = ws2.cell(row=row_num, column=1, value=label)
        cell_b = ws2.cell(row=row_num, column=2, value=value)
        if row_num == 1:
            cell_a.font = title_font
        elif label:
            cell_a.font = label_font

    wb.save(output_path)
    return output_path


# ── Quick test ────────────────────────────────────────────────
if __name__ == "__main__":
    test_data = [
        {"file": "student_0001.docx", "Name": "Tanishk Bansal",
         "Serial No.": "STU-2024-0001", "confidence": 1.0},
        {"file": "student_0002.docx", "Name": "Priya Sharma",
         "Serial No.": "STU-2024-0002", "confidence": 1.0},
        {"file": "student_0003.docx", "Name": "Rahul Verma",
         "Serial No.": "—",             "confidence": 0.5},
    ]
    path = export_to_excel(test_data, ["Name", "Serial No."])
    print(f"Excel created: {path}")